[package]
name = "keyer-generate"
version = "0.0.5"
authors = ["Alexey Korolev <alphatroya@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { version = "0.3" }
